name: Update GitHub Pages on Dispatch
permissions:
  contents: read
  pull-requests: write
  
on:
  repository_dispatch:
    types:
      - update-gh-pages

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the main repository
      uses: actions/checkout@v4
      with:
        repository: dparvin/EventLogHelper.CodeCoverage
        token: ${{ secrets.PAT_TOKEN }}

    - name: Prepare Pages content
      run: |
        mkdir -p coverage
        cp -a Pages/* coverage/

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: coverage

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
